### ISSUE TITLE
Using urlpath behind virtual nginx proxy

### ISSUE THREAD

**Issue by MelBourbon** [hackmdio/codimd-container#21]
I want to setup codimd-container behind a virtual nginx host with a suburl in the same manner I configured Wekan and Nextcloud. But opening server.mydomain.de/codimd shows only the top bar and for the rest I get "**404 not found oops**" warning.

I added `CMD_DOMAIN` and `CMD_URL_PATH` to the docker_compose.yml as shown below.

docker_compose.yml:

     Using version 3 to provide play-with-docker badge
     version: '3'
     app:
     image: hackmdio/hackmd:1.2.1
     environment:
      - CMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd
      - CMD_DOMAIN=server.mydomain.de
      - CMD_URL_PATH=server.mydomain.de/codimd

nginx virtual host:

    upstreao_nodes {
         ip_hash;
        server 127.0.0.1:3000;
    }

    location /codimd {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:3000;
        proxy_cache_bypass $http_upgrade;
        proxy_redirect off;
        }

**Comment by SISheogorath** [comment]
`CMD_URL_PATH` should be set to `/codimd` only. Also please not that this setting does not work with pre-build images. You have to build and own CodiMD image with those settings set in the `config.json`:

https://github.com/hackmdio/codimd-container/blob/master/resources/config.json

For more details, see existing issues like this one:

https://github.com/hackmdio/codimd/issues/616

**Comment by MelBourbon** [comment]
Thanks for your help. I already failed to build codimd by trying to install native. So this may be to complicate for my knowledge. I will try to get the docker running by using a subdomain without a subfolder.
