### ISSUE TITLE
How to set environment variables in codimd-container

### ISSUE THREAD

**Issue by MelBourbon** [hackmdio/codimd-container#22]
Sorry if this is a "stupid" question. But how can I set environment variables by using the codimd-container. I would like to set `CMD_ALLOW_EMAIL_REGISTER` to `false` for example. Do I need to built my own image? If yes how?

**Comment by SISheogorath** [comment]
This is easy and no worries, you don't have to rebuild an image to change a variable. I just assume you used the setup described in the README file and this way using docker-compose.

In this case you can just extend the environment part of the file here:
https://github.com/hackmdio/codimd-container/blob/9bd598de820de2a8e1386b1a88af4466dfac5845/docker-compose.yml#L65-L71


it should look like this afterwards:

```
    environment:
      # DB_URL is formatted like: <databasetype>://<username>:<password>@<hostname>/<database>
      # Other examples are:
      # - mysql://hackmd:hackmdpass@database:3306/hackmd
      # - sqlite:///data/sqlite.db (NOT RECOMMENDED)
      # - For details see the official sequelize docs: http://docs.sequelizejs.com/en/v3/
      - CMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd
      - CMD_ALLOW_EMAIL_REGISTER=false
```

**Comment by MelBourbon** [comment]
Perfect, thanks! Worked like described.
