### ISSUE TITLE
DB migration does not work with MariaDB on debian stable

### ISSUE THREAD

**Issue by simonszu** [hackmdio/codimd-container#7]
The DB migration on first install does not work with MariaDB which is provided with Debian Stable. The error i get is: 
`Unhandled rejection SequelizeDatabaseError: ER_INDEX_COLUMN_TOO_LONG: Index column size too large. The maximum column size is 767 bytes.`

This is a common issue with MariaDB <10.3 and can be fixed with some initial SQL statements:
```
SET GLOBAL innodb_file_format=Barracuda;
SET GLOBAL innodb_file_per_table=ON;
innodb_large_prefix=1
```
after that, the row size needs to be set to dynamic, this is ideally done with `ROW_FORMAT=DYNAMIC`. In MariaDB <10.3 this cannot be done globally but needs to be set on each `CREATE TABLE` statement individually.

**Comment by SISheogorath** [comment]
I think that's a general problem with our upstream, so let's close it here and tackle it in https://github.com/hackmdio/codimd/issues/1026
